[WIP]: #1089: IDE2 falls back to new sketch if opening failed.
arduino/arduino-ide pull request #1152
Opened 2022-07-06 15:07 UTC by kittaakos

### Motivation

### Change description

### Other information

Closes #1089

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2022-07-06 15:09 UTC, kittaakos commented on arduino-ide-extension/src/node/sketches-service-impl.ts
> +    err.message.toLocaleLowerCase('en-US').includes('not_found')
Probably superfluous: https://grpc.github.io/grpc/core/md_doc_statuscodes.html.

2022-07-06 15:10 UTC, kittaakos commented on arduino-ide-extension/src/common/protocol/sketches-service.ts
> +        data: { uri },
Consider including the file-system path? Would be obsolete with the next Theia version.

2022-07-06 15:10 UTC, kittaakos commented on arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
> +    }, 1_000);
on app `ready`?

2022-07-14 12:57 UTC, kittaakos commented on arduino-ide-extension/src/common/protocol/sketches-service.ts
> +        data: { uri },
350c04b0bc28bc57acb12d65c6b12cff1777ccea + https://github.com/arduino/arduino-cli/issues/1797

2022-07-14 12:58 UTC, kittaakos commented on arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
> +    }, 1_000);
ee17fd4

2022-07-15 02:21 UTC, per1234 requested changes
There are two distinct reasons the IDE might attempt to open a sketch:

- Explicit action by user (e.g., selecting a sketch from **File > Sketchbook**)
- Restore state from previous session (https://github.com/arduino/arduino-ide/pull/780)

The IDE must gracefully handle a failure of either operation (https://github.com/arduino/arduino-ide/issues/1089). However, I feel the need to communicate about the failure to the user differs between them.

If an operation triggered explicitly by the user fails, it is important to communicate this to the user. So I think showing a notification when the sketch opening fails is necessary in this case.

The situation is different when it comes to automatically opening sketches from the previous IDE session. This is only a convenience feature. If it is able to open the sketches, great. But if it is not able to open the sketches, I don't want to hear about it. I might have intentionally deleted that sketch. It might have been a new sketch that was staged in a temporary folder the OS cleaned up. In the latter case, the temporary path makes the error message especially cryptic:
![image](https://user-images.githubusercontent.com/8572152/179133865-07c33cb4-1485-4d02-806d-1c57acb98af6.png)

So I suggest that no error notification be shown when the sketch opening fails during the restore operation (logging it is fine of course).

2022-07-15 07:17 UTC, kittaakos commented
Thank you for the review!

> So I suggest that no error notification be shown when the sketch opening fails during the restore operation (logging it is fine of course).

Sure 👍 

IDE2 (and the CLI) might fail to load the sketch due to two reasons:
 - the sketch folder was deleted,
 - the sketch is not valid (the main file was deleted, does not match the folder name, .etc)

As a user, do you expect that IDE2 will omit the error notification in both cases?

2022-07-15 07:28 UTC, per1234 commented
>do you expect that IDE2 will omit the error notification in both cases?

In the case of a "restore" operation, yes.

2022-07-15 08:23 UTC, kittaakos commented
I have updated the PR not to show the error notification when restoring the previously opened sketch has failed (due to a missing or invalid sketch). I updated the screencasts too to show the expected IDE2 behavior. Please review.

2022-07-15 11:47 UTC, per1234 approved these changes
It works perfectly. Excellent work Akos!

2022-07-15 16:25 UTC, AlbyIanna approved these changes
LGTM.

I left some comments, but nothing important.

2022-07-15 16:25 UTC, AlbyIanna commented on arduino-ide-extension/src/browser/contributions/first-start-installer.ts
> +}
Make sure to remove this as we already put this code [into a separate contribution](https://github.com/arduino/arduino-ide/commit/73835eced3bda7657308bf582bd5e5690d73879a#diff-8e1a8da61c276800216f425dc94832341b6b2b17639b36e837399fb13102b128).

2022-07-18 07:58 UTC, kittaakos commented on arduino-ide-extension/src/browser/boards/boards-service-provider.ts
> +
Good idea, but I do not want to introduce a hard dependency between contributions. Also, this service does not contribute any commands, menu items, .etc.

2022-07-18 09:10 UTC, merged