[WIP]: Theia 1.27.0 signed
arduino/arduino-ide pull request #1241
Opened 2022-07-22 14:08 UTC by kittaakos

### Motivation

### Change description

### Other information

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2022-07-23 18:22 UTC, per1234 requested changes
### Describe the problem

Startup hangs at the splash screen:

![image](https://user-images.githubusercontent.com/8572152/180617990-16b241c5-29d1-4963-95f9-9366fdd6b150.png)

This happens even after clearing my `directories.data`, User Data Directory, Configuration Directory, and sketchbook. So it is not related to any special configuration or installations.

I don't see anything interesting looking in the logs:

```text
Starting backend process. PID: 13036
Using browser-only version of superagent in non-browser environment
Configuration directory URI: 'file:///c%3A/Users/per/.theia'
Configuring to accept webviews on '^.+\.webview\..+$' hostname.
2022-07-23T18:08:09.438Z root INFO Backend Object.initialize: 6.0 ms [Finished 11.884 s after backend start]
2022-07-23T18:08:09.438Z root INFO Backend Object.configure: 4.8 ms [Finished 11.884 s after backend start]
2022-07-23T18:08:09.438Z root INFO Backend MessagingContribution.onStart: 2.1 ms [Finished 11.884 s after backend start]
2022-07-23T18:08:09.439Z root INFO Backend OSBackendApplicationContribution.configure: 0.6 ms [Finished 12.308 s after backend start]
2022-07-23T18:08:09.439Z root INFO Backend DefaultWorkspaceServer.onStart: 0.5 ms [Finished 12.308 s after backend start]
2022-07-23T18:08:09.441Z root WARN Backend LocalizationBackendContribution.initialize took longer than the expected maximum 50 milliseconds: 424.0 ms [Finished 12.309 s after backend start]
2022-07-23T18:08:09.441Z root INFO Backend LocalizationBackendContribution.configure: 0.7 ms [Finished 12.309 s after backend start]
2022-07-23T18:08:09.442Z root INFO Backend TaskBackendApplicationContribution.onStart: 0.4 ms [Finished 12.309 s after backend start]
2022-07-23T18:08:09.443Z root INFO Backend PluginDeployerContribution.initialize: 1.3 ms [Finished 12.311 s after backend start]
2022-07-23T18:08:09.443Z root INFO Backend ElectronTokenBackendContribution.configure: 1.0 ms [Finished 12.311 s after backend start]
2022-07-23T18:08:09.444Z root INFO Backend ConfigServiceImpl.onStart: 1.5 ms [Finished 12.311 s after backend start]
2022-07-23T18:08:09.445Z root INFO Backend WebviewBackendSecurityWarnings.initialize: 0.7 ms [Finished 12.313 s after backend start]
2022-07-23T18:08:09.446Z root INFO Backend ArduinoDaemonImpl.onStart: 0.4 ms [Finished 12.313 s after backend start]
2022-07-23T18:08:09.446Z daemon INFO Starting daemon from E:\downloads\review\1241\1-bed8105\resources\app\node_modules\arduino-ide-extension\build\arduino-cli.exe...
2022-07-23T18:08:09.446Z root INFO Backend NodeFileUploadService.configure: 2.5 ms [Finished 12.315 s after backend start]
2022-07-23T18:08:09.446Z discovery-log INFO start
2022-07-23T18:08:09.446Z discovery-log INFO start new deferred
2022-07-23T18:08:09.446Z root INFO Backend BoardDiscovery.onStart: 0.6 ms [Finished 12.315 s after backend start]
2022-07-23T18:08:09.447Z root INFO Backend FileDownloadEndpoint.configure: 1.4 ms [Finished 12.317 s after backend start]
2022-07-23T18:08:09.447Z root INFO Backend AuthenticationServiceImpl.onStart: 0.1 ms [Finished 12.317 s after backend start]
2022-07-23T18:08:09.447Z root INFO Backend PluginApiContribution.configure: 0.6 ms [Finished 12.318 s after backend start]
2022-07-23T18:08:09.469Z root INFO Backend HostedPluginReader.configure: 0.3 ms [Finished 12.319 s after backend start]
2022-07-23T18:08:09.469Z root INFO Backend HostedPluginReader.configure: 0.2 ms [Finished 12.319 s after backend start]
2022-07-23T18:08:09.469Z root INFO Backend PlotterBackendContribution.configure: 22.0 ms [Finished 12.341 s after backend start]
2022-07-23T18:08:09.473Z root INFO Theia app listening on http://localhost:1697.
2022-07-23T18:08:09.474Z root INFO Finished starting backend application: 27.2 ms [Finished 12.345 s after backend start]
2022-07-23T18:08:09.817Z root WARN The local plugin referenced by local-dir:/c%3A/Users/per/.arduinoIDE/plugins does not exist.
2022-07-23T18:08:09.817Z root WARN The local plugin referenced by local-dir:/c%3A/Users/per/.arduinoIDE/extensions does not exist.
2022-07-23T18:08:09.818Z root WARN The local plugin referenced by local-dir:C:\Users\per\.arduinoProIDE\plugins does not exist.
2022-07-23T18:08:09.826Z root ERROR ---- !!!SLOW!!! DURATION: loadCliConfig took 387.576 ms. Args: [] ----
2022-07-23T18:08:11.042Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.043Z root INFO Resolved "cortex-debug" to a VS Code extension "cortex-debug@0.3.10" with engines:
2022-07-23T18:08:11.043Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.043Z root INFO Resolved "vscode-arduino-tools" to a VS Code extension "vscode-arduino-tools@0.0.2-beta.4" with engines:
2022-07-23T18:08:11.043Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.043Z root INFO Resolved "vscode-builtin-cpp" to a VS Code extension "cpp@1.52.1" with engines:
2022-07-23T18:08:11.043Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.043Z root INFO Resolved "vscode-builtin-json" to a VS Code extension "json@1.46.1" with engines:
2022-07-23T18:08:11.043Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.043Z root INFO Resolved "vscode-builtin-json-language-features" to a VS Code extension "json-language-features@1.46.1" with engines:
2022-07-23T18:08:11.044Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.044Z root INFO Resolved "vscode-language-pack-cs" to a VS Code extension "vscode-language-pack-cs@1.69.0" with engines:
2022-07-23T18:08:11.044Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.044Z root INFO Resolved "vscode-language-pack-de" to a VS Code extension "vscode-language-pack-de@1.69.0" with engines:
2022-07-23T18:08:11.044Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.044Z root INFO Resolved "vscode-language-pack-es" to a VS Code extension "vscode-language-pack-es@1.69.0" with engines:
2022-07-23T18:08:11.044Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.044Z root INFO Resolved "vscode-language-pack-fr" to a VS Code extension "vscode-language-pack-fr@1.69.0" with engines:
2022-07-23T18:08:11.044Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.044Z root INFO Resolved "vscode-language-pack-it" to a VS Code extension "vscode-language-pack-it@1.69.0" with engines:
2022-07-23T18:08:11.045Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.045Z root INFO Resolved "vscode-language-pack-ja" to a VS Code extension "vscode-language-pack-ja@1.69.0" with engines:
2022-07-23T18:08:11.045Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.045Z root INFO Resolved "vscode-language-pack-nl" to a VS Code extension "vscode-language-pack-nl@1.48.3" with engines:
2022-07-23T18:08:11.045Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.045Z root INFO Resolved "vscode-language-pack-pt-BR" to a VS Code extension "vscode-language-pack-pt-BR@1.69.0" with engines:
2022-07-23T18:08:11.045Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.045Z root INFO Resolved "vscode-language-pack-ru" to a VS Code extension "vscode-language-pack-ru@1.69.0" with engines:
2022-07-23T18:08:11.045Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.046Z root INFO Resolved "vscode-language-pack-tr" to a VS Code extension "vscode-language-pack-tr@1.69.0" with engines:
2022-07-23T18:08:11.046Z root INFO PluginTheiaDirectoryHandler: accepting plugin with path
2022-07-23T18:08:11.046Z root INFO Resolved "vscode-language-pack-zh-hans" to a VS Code extension "vscode-language-pack-zh-hans@1.69.0" with engines:
2022-07-23T18:08:11.058Z root INFO Resolve plugins list: [...]

2022-07-25 07:06 UTC, kittaakos commented
Thank you for giving it a try. The cause of the problem must be the workaround from #1160. I'll look into it.

2022-07-25 11:59 UTC, kittaakos commented
Another problem I have noticed with latest Theia is the duplicate editor tabs 😅 

<img width="791" alt="Screen Shot 2022-07-25 at 13 58 01" src="https://user-images.githubusercontent.com/1405703/180772699-524d86f8-1aaf-4a30-a8e0-7f9948a6b002.png">

2022-07-26 08:46 UTC, kittaakos commented
This is a known issue in Theia that could block the version update in IDE2: https://github.com/eclipse-theia/theia/issues/11442

@fstasi, @ubidefeo

2022-09-21 09:55 UTC, kittaakos commented
I am closing it as obsolete. [`@theia/core@1.29.0`](https://www.npmjs.com/package/@theia/core/v/1.29.0) is already out, and IDE2 does not want to bump to `1.27.0` anymore.

2022-09-21 09:55 UTC, closed without merging