#118 Link compiler errors to editor.
arduino/arduino-ide pull request #1275
Opened 2022-08-02 10:32 UTC by kittaakos

### Motivation
Can jump from the error location from the _Output_.

### Change description
TODO:

### Other information

Closes #118

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2022-08-03 14:36 UTC, per1234 requested changes
### Describe the problem

On my Windows machine, clicking the "**Reveal Error**" link or using the <kbd>Ctrl</kbd>+click shortcut does not result in the cursor moving to the file and line specified in the error message.

### To reproduce

1. Compile a sketch that will produce an error:
```cpp
void setup() {
  someerror
}
void loop() {
  anothererror
}
```
**ⓘ** I provided a short sketch that will produce two errors to keep the demo simple, but I also have the same problem with smaller and larger multi-file sketches.
1. Hover the mouse pointer above one of the underlined links in the output:
```text
C:\Users\per\Documents\Arduino\Error\Error.ino: In function 'void loop()':
C:\Users\per\Documents\Arduino\Error\Error.ino:5:3: error: 'anothererror' was not declared in this scope
   anothererror
   ^~~~~~~~~~~~
C:\Users\per\Documents\Arduino\Error\Error.ino:5:3: note: suggested alternative: 'strerror'
   anothererror
   ^~~~~~~~~~~~
   strerror
```
1. Click the "**Reveal Error**" link.

🐛 The cursor is not moved to the line of the sketch associated with the error message.

### Expected behavior

Cursor is moved to the line of the sketch associated with the error message after clicking the "**Reveal Error**" link or doing a <kbd>Ctrl</kbd>+click.

### Arduino IDE version

2.0.0-rc9-snapshot-0c9e1ab

### Operating system

Windows

### Operating system version

10

### Additional context

It works fine on my Linux machine.

---

I see the following logs in the Developer Tools console after clicking the "**Reveal Error**" link:

```text
logger-protocol.ts:110 root INFO compiler-errors Current error changed to c;58
logger-protocol.ts:110 root INFO compiler-errors Handling selection change in editor file:///c%3A/Users/per/Documents/Arduino/Error/Error.ino. New (monaco) selection: [2,3 -> 2,3]
logger-protocol.ts:110 root WARN compiler-errors Failed to mark error c;59 as the current one. Error is unknown. Known errors are: c;58,c;59
e.log @ logger-protocol.ts:110
(anonymous) @ logger-frontend-module.ts:41
(anonymous) @ logger.ts:312
(anonymous) @ logger.ts:304
Promise.then (async)
log @ logger.ts:299
i @ logger.ts:45
markAsCurrentError @ compiler-errors.ts:655
execute @ compiler-errors.ts:267
executeCommand @ command.ts:336
async function (async)
executeCommand @ command.ts:335
open @ command-open-handler.ts:50
t.open @ opener-service.ts:90
async function (async)
t.open @ opener-service.ts:89
interceptOpen @ monaco-editor-provider.ts:208
open @ monaco-editor-provider.ts:153
(anonymous) @ openerService.ts:173
(anonymous) @ markerDecorations.ts:26
r @ markerDecorations.ts:26
open @ openerService.ts:160
callback @ markdownRenderer.ts:100
(anonymous) @ markdownRenderer.ts:206
(anonymous) @ event.ts:128
invoke @ event.ts:569
fire @ event.ts:736
o @ event.ts:37
```

I do not see this "Failed to mark error" line in the console on my Linux machine.

2022-08-03 14:52 UTC, per1234 requested changes
### Describe the problem

Scrolling the output view up at the end of the compilation can cause the link to be placed on the wrong line.

This is fairly minor and is likely to be rarely produced by the user. I did encounter it purely by chance on the first test on my Linux machine, so thought it was at least worth mentioning, but I don't think it is worth spending a lot of time on if it is challenging.

### To reproduce

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Check the box next to **Show verbose output during > ☐ compile**.
1. Click the <kbd>**OK**</kbd> button.
1. Compile a sketch that will produce an error:
   ```cpp
   void setup() {
     someerror
   }
   void loop() {}
   ```
1. As soon as the compilation process finishes, scroll the output view up to the top.

🐛 If the timing was correct, one of the lines of the compilation commands will be linked instead of the expected error message line:

![image](https://user-images.githubusercontent.com/8572152/182639538-e0c3f1df-dd8f-4c34-87aa-9809db509e09.png)

### Expected behavior

The link is placed on the error message.

### Arduino IDE version

2.0.0-rc9-snapshot-0c9e1ab

### Operating system

Ubuntu 20.04

### Additional context

I have not been able to produce this on my Windows machine.

I notice that the compilation command stdout lines are mixed up with the stderr lines, while on my Windows machine all the stdout is printed before the start of the stderr. So perhaps this is the explanation for the different results between the two machines?

2022-08-03 15:23 UTC, per1234 requested changes
### Describe the problem

When a sketch file contains multiple error highlights, the selection is lost at each highlighted line while selecting in an upward direction.

### To reproduce

1. Compile a sketch that will produce errors on multiple lines of a single file:
   ```cpp
   void setup() {
     fooError
   }
   void loop() {
     barError
   }
   ```
1. Wait for the compilation process to fail, as expected.
1. Click at the bottom area of the editor view and drag the mouse pointer upwards to select the sketch code.

🐛 The selection is lost as the mouse pointer crosses each of the highlighted lines:

![sm-focus](https://user-images.githubusercontent.com/8572152/182646355-f78eb770-904c-4286-beb8-4f773f4ed432.gif)

### Expected behavior

Selecting sketch code text is not affected by the error line highlights.

### Arduino IDE version

2.0.0-rc9-snapshot-0c9e1ab

### Operating system

Windows 10, Ubuntu 20.04

### Additional context

The issue also occurs when selecting via the <kbd>**Shift**</kbd>+<kbd>**↑**</kbd> keyboard shortcut.

The issue does not occur when selecting by click and drag in a downwards direction.

The issue does not occur when selecting via the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**Home**</kbd> keyboard shortcut.

---

I notice that multiple error lines are now highlighted, whereas with previous versions of the Arduino IDE (going all the way back to the introduction of the feature at https://github.com/arduino/arduino-ide/commit/4611381a382ec2478f9cde19f6eed4dcc8d5954f), only a single line was highlighted unless the `arduino.compile.experimental` advanced setting was enabled. Since the issue only occurs when there are multiple highlights, I thought this observation it was worth mentioning.

For some reason, the error highlight at line 5 does not appear in the screencast above, even though I can see it on my monitor:

![image](https://user-images.githubusercontent.com/8572152/182646319-9a3838d7-0e3a-4c9b-9dce-cfbf21e45981.png)

2022-08-11 10:20 UTC, kittaakos commented
> On my Windows machine, clicking the "**Reveal Error**" link or using the Ctrl+click shortcut does not result in the cursor moving to the file and line specified in the error message.

It should be fixed now.

> Scrolling the output view up at the end of the compilation can cause the link to be placed on the wrong line.

It was unrelated to the scrolling, but it should work correctly now.

> I notice that multiple error lines are now highlighted, whereas with previous versions of the Arduino IDE (going all the way back to the introduction of the feature at [4611381](https://github.com/arduino/arduino-ide/commit/4611381a382ec2478f9cde19f6eed4dcc8d5954f)), only a single line was highlighted unless the `arduino.compile.experimental` advanced setting was enabled.

This change is required to support all error links from the output, not only one 😬 . I can add the technical explanation on why if required. @per1234, do you prefer to show only one error (highlighted with the "red" line) even if there are multiple errors? It's not a trivial task but probably doable. Thank you!

> When a sketch file contains multiple error highlights, the selection is lost at each highlighted line while selecting in an upward direction.

I could not reproduce it on both macOS and Windows so far.

2022-08-11 15:46 UTC, kittaakos commented
> > When a sketch file contains multiple error highlights, the selection is lost at each highlighted line while selecting in an upward direction.
> 
> I could not reproduce it on both macOS and Windows so far.

I still could not reproduce it.

Per, if you have some time, please give the updated version a try. I still see some issues when deleting content from the editor, the markers are not removed correctly. I try to find a solution and/or document the known issues. Upstream: https://github.com/microsoft/monaco-editor/issues/2138

2022-08-11 17:12 UTC, per1234 approved these changes
The problems I reported in my previous review are now resolved and everything is working perfectly for me.

This is sure to greatly enhance the user experience when developing larger sketches.

Thanks Akos!

2022-08-11 17:16 UTC, per1234 commented
>I still could not reproduce it.

I can reproduce it consistently on both Windows and Linux when using 2.0.0-rc9-snapshot-0c9e1ab (the build from https://github.com/arduino/arduino-ide/commit/fef76f2349d341478b3e528aa9f2ed57f77ca0bf). I can not reproduce it when using the build from https://github.com/arduino/arduino-ide/pull/1275/commits/5b6580c6a4c6949ca66db109e285feeb7ae989b9, so it must have been fixed inadvertently by some of the changes you made between those revisions.

>do you prefer to show only one error (highlighted with the "red" line) even if there are multiple errors?

I don't have a strong preference either way. I only mentioned the change because it seemed possibly related to the lost selection bug.

2022-08-15 14:55 UTC, merged