Error message if upload is not possible
arduino/arduino-ide pull request #1353
Opened 2022-08-25 11:32 UTC by francescospissu

### Motivation
If the user presses the upload button and no board is selected, a message should appear warning what went wrong while uploading. Since verify takes place before upload, the same message that is given when the user tries to compile a sketch without selecting a board should be shown. On the other hand, this message is not very clear, so it should be updated.

### Change description
Communicate to user when upload is impossible due to no board selection.
Make error message from compiling without board selected more user friendly.

### Other information
Closes #845.
Closes #62.

This fix depends on the changes made here: https://github.com/arduino/arduino-cli/pull/1848. Without it it is not possible to verify that #62 is resolved.

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2022-08-25 12:45 UTC, kittaakos approved these changes
The code looks good to me.

I am not familiar with the board user fields logic, maybe we should change

```ts
if (this.boardRequiresUserFields && !this.cachedUserFields.has(key)) {
```

to 

```ts
```

2022-08-25 14:30 UTC, ubidefeo approved these changes
Works as expected

2022-08-25 14:31 UTC, davegarthsimpson approved these changes

2022-08-25 19:41 UTC, per1234 requested changes

2022-08-25 19:41 UTC, per1234 commented on arduino-ide-extension/src/browser/contributions/contribution.ts
> +          'No board selected. Please select your Arduino board from the Tools > Board menu.';
```suggestion
        message = nls.localize(
          'arduino/coreContribution/noBoardSelected',
          'No board selected. Please select your Arduino board from the Tools > Board menu.'
        );
```

2022-08-26 08:23 UTC, francescospissu commented on arduino-ide-extension/src/browser/contributions/contribution.ts
> +          'No board selected. Please select your Arduino board from the Tools > Board menu.';
Thanks for your suggestion @per1234!

2022-08-26 09:00 UTC, per1234 approved these changes
Thanks Francesco!

2022-08-26 09:24 UTC, merged