#1431 Add missing translations
arduino/arduino-ide pull request #1449
Opened 2022-09-16 14:48 UTC by kittaakos

### Motivation

Add the missing translations.

TODOs for @kittaakos 
 - [ ] List each item with a screenshot that was fixed,
 - [ ] Squash commits. Currently commits help to list the fixed items.

### Change description

### Other information

Closes #1431

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2022-09-20 10:26 UTC, AlbyIanna approved these changes
Code looks good to me ✅

2022-09-21 08:00 UTC, kittaakos commented
This PR should contain #1462.

2022-09-22 10:58 UTC, per1234 requested changes

2022-09-22 10:58 UTC, per1234 commented on arduino-ide-extension/src/node/i18n/arduino-localization-contribution.ts
> +    ['pl', 'pl'],
```suggestion
    ['pl'],
    ['pt-br', 'pt'],
```

- Use alphabetical order as specified in the comment
- Remove superfluous second element for Polish

2022-09-26 08:48 UTC, per1234 approved these changes
Approved code changes and behaviour. Thanks Akos!

2022-09-26 08:49 UTC, merged