Avoid intellisense widgets being covered by the bottom panel
arduino/arduino-ide pull request #1479
Opened 2022-09-21 15:17 UTC by r3inbowari

### Motivation
Avoid the problem that the Intellisense widget may be cover by the bottom(Output) panel partially.

### Change description
from: 
![image](https://user-images.githubusercontent.com/30739857/191543229-f999a7b7-1bb7-467e-8032-43831bec27ed.png)

to: 
![image](https://user-images.githubusercontent.com/30739857/191541944-760fc791-d22b-48df-960f-012c760abf47.png)

### Other information

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2022-09-22 07:45 UTC, AlbyIanna requested changes
Thanks for your contribution @r3inbowari!

Your change fixes the issue, although I would prefer increasing the `z-index` of the `#theia-main-content-panel` instead of setting a negative value for the `#theia-bottom-content-panel`. This way, we make sure that any sibiling of the main content panel will have a lower z-index than its own – for example, in the situation we add a new widget there, we would incur in the same issue again.

Something like this should work:
```
#theia-main-content-panel {
  z-index: 1
}
```

2022-09-22 10:43 UTC, r3inbowari commented
Agree :) Also fixed SplitPanel-handle showing above intellisense widget.

from:
![1663842466981](https://user-images.githubusercontent.com/30739857/191725887-daabefb9-1ea4-48a8-942a-8c1eaf42f13f.jpg)

to:
![1663842423909](https://user-images.githubusercontent.com/30739857/191725839-aeb3cc21-7419-40e4-9f2f-c8d172b9cd16.jpg)

2022-09-22 10:49 UTC, AlbyIanna commented
This looks even better! I tested it and it works perfectly 😺 
Thank you so much!

2022-09-22 10:49 UTC, AlbyIanna approved these changes

2022-09-27 13:19 UTC, per1234 approved these changes
Thanks @r3inbowari!

2022-09-27 13:19 UTC, merged