let the user edit the stepper input with keyboard
arduino/arduino-ide pull request #1547
Opened 2022-10-07 16:31 UTC by AlbyIanna

### Motivation
It's difficult for the user to edit the font size in the preferences using the keyboard.

On the current state, when a user tries to edit the value of the font size with the keyboard, the value would update unexpectedly.

For example:
- the font size is 72
- focus the input field
- press BACKSPACE
- expected: the font size is 7; result: the font size is 8 😢 
- now press 1
- expected: the font size is 81; result: the font size is 72 😢 

The reason is we validate the user input _as they type_, and if the input is invalid, we change the value to a valid one.

### Change description
With this change, I want to validate the user input _as they finished typing_ instead of _as they type_. In order to achieve that, I used the `onBlur` callback of the input field, so that the user can type whatever they want in the input field (only numbers, to be precise), and as soon as their focus change from the input field to another element (e.g.: they click on any other piece of UI or press ESCAPE) we validate the input they just typed in and, if necessary, change it to a valid value.

<details>
  <summary>Before the change (video):</summary>

https://user-images.githubusercontent.com/6939054/194602614-cc7f3ce5-b45e-49c5-83d5-ac0c553d7b9a.mov

</details>

<details>
  <summary>After the change (video):</summary>

https://user-images.githubusercontent.com/6939054/194602625-cf8fe2f3-ede7-4b6d-b791-9f5296f1c442.mov

</details>

### Other information
Fixes #1542 

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2022-10-11 15:45 UTC, davegarthsimpson requested changes
unfortunately there are a few issues here:

1. This breaks the arrow buttons functionality in general due to the wrong value being referenced in the `onStep` function
2. It results in a buggy feeling UX if the user clicks an arrow when the input value is '0' or '-' (the blur restores the initial value and then "steps it"), in the below changes I've made sure to disable the steppers when an invalid value is in the input
3. the value is passed as prop from the parent, when it changes it should reset the internal state, we should use the concept of an `initialValue` together with a key attribute in the stepper JSX to achieve this, the internal state does not need to be updated when `setSettingsStateValue` is invoked as doing should trigger a reset anyway

I pushed some changes to a different branch here which resolve the above:
https://github.com/arduino/arduino-ide/commit/ce3b47bad4b855b11a83f4d09c568a02c93254b7
There is also a small styling change as I noticed the position of the arrow buttons container was wrong in the font size stepper.

2022-10-19 13:33 UTC, francescospissu commented
It works well for me. The only small problem I encountered occurs when an invalid value is entered in the input field when the current value is the minimum (font size 8), in this case the input value is not automatically updated as entering an invalid value while the current value is greater than the minimum.

See the video:

https://user-images.githubusercontent.com/94986937/196705524-23a51dcf-e990-4425-bb80-e159eba1103c.mp4

2022-10-20 07:37 UTC, AlbyIanna commented
> It works well for me. The only small problem I encountered occurs when an invalid value is entered in the input field when the current value is the minimum (font size 8), in this case the input value is not automatically updated as entering an invalid value while the current value is greater than the minimum.

Nice catch! I just pushed a fix 👍

2022-10-20 08:22 UTC, kittaakos commented
I did not check the code changes thoroughly, but the behavior only. If I set the font size to 73 which exceeds 72 and set enter, the new value will be 72. If I set the value to 0, nothing changes. I expected symmetrical behavior; setting the value to 0 will set the font size to min; 8.

2022-10-20 08:25 UTC, davegarthsimpson requested changes
```
 const setValidValue = (value: number): void => {
    const clampedValue = clamp(value, minValue, maxValue);
    setValueState({ currentValue: clampedValue, isEmptyString: false });
    setSettingsStateValue(clampedValue);
  };
```

this doesn't feel right, if the value has changed `setSettingsStateValue` resets the whole component as well as the internal state, thus setting the internal state shouldn't be necessary

2022-10-20 08:27 UTC, kittaakos approved these changes
It works for me. Thank you!

2022-10-20 08:27 UTC, kittaakos commented on arduino-ide-extension/src/browser/style/settings-step-input.css
> +}
_No newline at the end of file_

2022-10-20 08:30 UTC, AlbyIanna commented
> this doesn't feel right, if the value has changed setSettingsStateValue resets the whole component as well as the internal state (because it changes the jsx key), thus setting the internal state shouldn't be necessary, if we're having to do this things are likely muddled and we probably need to rethink the lifecycle

Ok, I'll look into it better later 👍

2022-10-21 09:59 UTC, AlbyIanna commented
@francescospissu would you please give it another try? @davegarthsimpson just pushed a fix.

2022-10-21 14:56 UTC, francescospissu approved these changes
Now it works perfectly for me. Thanks @AlbyIanna 🙂

2022-10-21 15:27 UTC, davegarthsimpson approved these changes

2022-10-21 15:36 UTC, merged