test: added compiler test to verify IDE2's build path calculation is in sync with the CLI
arduino/arduino-ide pull request #1823
Opened 2023-01-19 15:22 UTC by kittaakos

## Depends on #1809

### Motivation

IDE2 wants to provide better UX when debugging an uncompiled sketch (#808). IDE2 must detect erroneous CLI behavior and provide user-friendly actions to achieve this. Currently, it's not trivial to detect the cause of an error (https://github.com/arduino/arduino-cli/issues/1762, https://github.com/arduino/arduino-cli/issues/1968#issuecomment-1306936142) so IDE2 tries to rely on filesystem path detected in the error messages. When the CLI compiles a sketch, it puts the build output into the temp folder. IDE2 tries to guess these temp folder paths from the location of the sketches on the filesystem. Sometimes, there is no deterministic way to determine the temp build output path. There are situations when it's only a guess. See here: https://github.com/arduino/arduino-ide/pull/1809#pullrequestreview-1249856385. This PR enables compiler tests using the gRPC client to make sure the IDE2 build output path calculation behaves the same as the CLI's.

### Change description

 - I removed the `ready` deferred promise from the core client provider. It broke the test, and it turned out to be not used. This PR cleans it up.
 - Split up the suites into tests (`yarn test`) and slow tests (`yarn test:slow`). For example, slow tests do not run when checking internationalization on the CI. (Ideally, no tests were executed on internationalization checks, but it's a different story.) Slow tests must use the `*.slow-test.ts` glob.
 - Inject interface instead of the concrete implementation into the sketches service.

### Other information

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2023-01-20 07:34 UTC, kittaakos commented on arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts
> +    bind(TheiaEnvVariablesServer).toService(EnvVariablesServer);
It looks incorrect:

```
ino-ide-extension: Configuration directory URI: 'file:///c%3A/Users/kittaakos/.theia'
```

2023-01-20 09:27 UTC, kittaakos commented on arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts
> +    bind(TheiaEnvVariablesServer).toService(EnvVariablesServer);
It's some trash logged to the console. It's from [here](https://github.com/eclipse-theia/theia/blob/3b4fb797eb9908f9c0b9f2e3fafa0255ee8054fe/packages/core/src/node/env-variables/env-variables-server.ts#L34). The tests eventually do not use this location. Check the existence of `~/.theia/arduino-cli.yaml`; it's not there. Run the tests: `yarn test:slow`, and check again `~/.theia/arduino-cli.yaml`. It's still not there.

2023-01-23 14:02 UTC, per1234 requested changes
I can do this:

1. Make fresh clone of `arduino/arduino-ide` repo.
2. Run `yarn` in the repo.
3. Run `yarn test:slow`

The tests run as expected.

But if I do the rest of the steps to run the application before attempting to run the tests:

1. Make fresh clone of `arduino/arduino-ide` repo.
2. Run `yarn` in the repo.
3. Run `yarn test:slow`
1. Run `yarn yarn rebuild:browser`
2. Run `yarn rebuild:electron`
3. Run `yarn test:slow`

Then it fails:

```text
$ yarn test:slow
yarn run v1.22.19
$ lerna run test:slow
lerna notice cli v6.1.0
lerna info versioning independent

> arduino-ide-extension:"test:slow"

$ mocha "./lib/test/**/*.slow-test.js"
arduino-ide-extension: Error: Module did not self-register: '/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/drivelist/build/Release/drivelist.node'.
arduino-ide-extension:     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
arduino-ide-extension:     at Module.load (node:internal/modules/cjs/loader:1043:32)
arduino-ide-extension:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
arduino-ide-extension:     at Module.require (node:internal/modules/cjs/loader:1067:19)
arduino-ide-extension:     at require (node:internal/modules/cjs/helpers:103:18)
arduino-ide-extension:     at bindings (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/bindings/bindings.js:112:48)
arduino-ide-extension:     at Object.<anonymous> (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/drivelist/js/index.js:25:27)
arduino-ide-extension:     at Module._compile (node:internal/modules/cjs/loader:1165:14)
arduino-ide-extension:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
arduino-ide-extension:     at Module.load (node:internal/modules/cjs/loader:1043:32)
arduino-ide-extension:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
arduino-ide-extension:     at Module.require (node:internal/modules/cjs/loader:1067:19)
arduino-ide-extension:     at require (node:internal/modules/cjs/helpers:103:18)
arduino-ide-extension:     at Object.<anonymous> (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/@theia/core/lib/node/env-variables/env-variables-server.js:31:19)
arduino-ide-extension:     at Module._compile (node:internal/modules/cjs/loader:1165:14)
arduino-ide-extension:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
arduino-ide-extension:     at Module.load (node:internal/modules/cjs/loader:1043:32)
arduino-ide-extension:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
arduino-ide-extension:     at Module.require (node:internal/modules/cjs/loader:1067:19)
arduino-ide-extension:     at require (node:internal/modules/cjs/helpers:103:18)
arduino-ide-extension:     at Object.<anonymous> (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/arduino-ide-extension/lib/node/theia/env-variables/env-variables-server.js:15:32)
arduino-ide-extension:     at Module._compile (node:internal/modules/cjs/loader:1165:14)
arduino-ide-extension:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
arduino-ide-extension:     at Module.load (node:internal/modules/cjs/loader:1043:32)
arduino-ide-extension:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
arduino-ide-extension:     at Module.require (node:internal/modules/cjs/loader:1067:19)
arduino-ide-extension:     at require (node:internal/modules/cjs/helpers:103:18)
arduino-ide-extension:     at Object.<anonymous> (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/arduino-ide-extension/lib/test/node/core-service-impl.slow-test.js:34:32)
arduino-ide-extension:     at Module._compile (node:internal/modules/cjs/loader:1165:14)
arduino-ide-extension:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
arduino-ide-extension:     at Module.load (node:internal/modules/cjs/loader:1043:32)
arduino-ide-extension:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
arduino-ide-extension:     at Module.require (node:internal/modules/cjs/loader:1067:19)
arduino-ide-extension:     at require (node:internal/modules/cjs/helpers:103:18)
arduino-ide-extension:     at requireOrImport (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/mocha/lib/esm-utils.js:15:12)
arduino-ide-extension:     at Object.exports.loadFilesAsync (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/mocha/lib/esm-utils.js:28:26)
arduino-ide-extension:     at Mocha.loadFilesAsync (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/mocha/lib/mocha.js:386:19)
arduino-ide-extension:     at singleRun (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/mocha/lib/cli/run-helpers.js:149:15)
arduino-ide-extension:     at exports.runMocha (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/mocha/lib/cli/run-helpers.js:186:11)
arduino-ide-extension:     at Object.exports.handler (/mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/mocha/lib/cli/run.js:319:11)
arduino-ide-extension:     at /mnt/1c0bd221-e077-452c-b688-160dc700c122/git/arduino-ide/node_modules/mocha/node_modules/yargs/lib/command.js:241:49
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Running target "arduino-ide-extension:test:slow" failed

   Failed tasks:
   
   - arduino-ide-extension:test:slow
   
   Hint: run the command with --verbose for more details.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This problem happens on my Windows 11 and my Ubuntu 22.04 machines (I didn't check on macOS).

Am I doing something silly @kittaakos?

2023-01-23 15:11 UTC, kittaakos commented
Great that you have asked! It's expected.

The tests should execute again if you switch back to the "browser" (Node.js from your `$PATH`) version:

```
yarn rebuild:browser && yarn test:slow
```

<details><summary>Click for full output</summary>
<p>

```
a.kitta@Akoss-MacBook-Pro tmp % rm -rf ./arduino-ide 
a.kitta@Akoss-MacBook-Pro tmp % git clone https://github.com/arduino/arduino-ide --single-branch --branch compile-test --depth 1 -qq
a.kitta@Akoss-MacBook-Pro tmp % cd arduino-ide 
a.kitta@Akoss-MacBook-Pro arduino-ide % yarn && yarn test:slow && yarn rebuild:electron && yarn test:slow
yarn install v1.22.18
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "@types/react@18.0.0" is incompatible with requested version "@types/react@^18.0.15"
warning Resolution field "@types/react-dom@18.0.0" is incompatible with requested version "@types/react-dom@^18.0.6"
warning Resolution field "@types/react@18.0.0" is incompatible with requested version "@types/react@^17"
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > @theia/electron@1.31.1" has unmet peer dependency "electron@^15.3.5".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > @tippyjs/react@4.2.6" has unmet peer dependency "react@>=16.8".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > @tippyjs/react@4.2.6" has unmet peer dependency "react-dom@>=16.8".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-disable@0.1.1" has unmet peer dependency "react@>=16".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-markdown@8.0.3" has unmet peer dependency "react@>=16".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select@5.6.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select@5.6.0" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-tabs@3.2.3" has unmet peer dependency "react@^16.3.0 || ^17.0.0-0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-virtualized@9.22.3" has unmet peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-virtualized@9.22.3" has unmet peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-window@1.8.8" has unmet peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-window@1.8.8" has unmet peer dependency "react-dom@^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > @theia/debug > requestretry@7.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > @theia/electron > @electron/remote@2.0.8" has unmet peer dependency "electron@>= 13.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select > @emotion/react@11.10.5" has unmet peer dependency "react@>=16.8.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select > react-transition-group@4.4.2" has unmet peer dependency "react@>=16.6.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select > react-transition-group@4.4.2" has unmet peer dependency "react-dom@>=16.6.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select > use-isomorphic-layout-effect@1.1.2" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > electron-app > @theia/process > node-pty@0.11.0-beta17" has incorrect peer dependency "node-gyp@^8.3.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select > @emotion/react > @emotion/babel-plugin@11.10.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select > @emotion/react > @emotion/use-insertion-effect-with-fallbacks@1.0.0" has unmet peer dependency "react@>=16.8.0".
warning "workspace-aggregator-df280727-2aba-4a09-8699-b069221727f7 > arduino-ide-extension > react-select > @emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
[5/5] 🔨  Building fresh packages...
$ lerna run prepare && yarn download:plugins
lerna notice cli v6.1.0
lerna info versioning independent

 >  Lerna (powered by Nx)   Running target prepare for 2 project(s):

    - arduino-ide-extension
    - electron-app

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> arduino-ide-extension:prepare

(node:34287) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34287) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:34287) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:34287) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
yarn run v1.22.18
$ yarn download-cli && yarn download-fwuploader && yarn download-ls && yarn copy-i18n && yarn clean && yarn download-examples && yarn build && yarn test
$ node ./scripts/download-cli.js
arduino-ide-extension: 📦  Identified released version of the CLI. Downloading version 0.29.0 from 'https://downloads.arduino.cc/arduino-cli/arduino-cli_0.29.0_macOS_64bit.tar.gz'
arduino-ide-extension: >>> Downloading from 'https://downloads.arduino.cc/arduino-cli/arduino-cli_0.29.0_macOS_64bit.tar.gz'...
arduino-ide-extension: <<< Download succeeded.
arduino-ide-extension: >>> Decompressing...
arduino-ide-extension: <<< Decompressing succeeded.
arduino-ide-extension: Done: /Users/a.kitta/Desktop/tmp/arduino-ide/arduino-ide-extension/build/arduino-cli
$ node ./scripts/download-fwuploader.js
arduino-ide-extension: 📦  Identified released version of the Firmware Uploader. Downloading version 2.2.2 from 'https://downloads.arduino.cc/arduino-fwuploader/arduino-fwuploade [...]

2023-01-23 15:53 UTC, per1234 approved these changes
Thanks so much for the excellent explanation Akos.

This test is great because we would be unlikely to catch a regression via manual testing.

2023-01-24 08:06 UTC, merged