[ATL-1107][ATL-1045] Verify/Upload Buttons Hover & "running" style
arduino/arduino-ide pull request #197
Opened 2021-03-10 14:20 UTC by fstasi

Creating another PR as I accidentally merged #190 

This PR is an amend to the previous one, containing fixes after @kittaakos review

I Will **squash merge** this PR into main once the review is over, in order to have a single commit on the main branch

2021-03-10 14:30 UTC, kittaakos commented on arduino-ide-extension/src/browser/contributions/upload-sketch.ts
> +        }
> but the check whether or not continue with the action should be inside the action handler itself, in my opinion.

It is there; you added the `isEnabled` method: https://github.com/arduino/arduino-ide/pull/197/files#diff-5c246e36e23a59755c9cc7d5a116eac5be34d188c0eb681f8c449915cbfe9aacR30.

In theory, if the command handler is not enabled, the command should not run. I am fine with this approach. I just wanted to know if you did hit an error or why did you add it.

2021-03-12 14:47 UTC, kittaakos commented
@fstasi, if the PR is ready for review, please quash the commits, and I look into it. Thank you!

2021-03-15 08:30 UTC, fstasi commented
> @fstasi, if the PR is ready for review, please quash the commits, and I look into it. Thank you!

@kittaakos sqashed and ready for review :)

2021-03-15 09:51 UTC, kittaakos commented
I have a few remarks on the behavior:

 - The toolbar color is not yellow when executing the command and hovering the toolbar. See the screencast. Once I have clicked on it, I have to un-hover the toolbar to see that it's yellow.

![screencast 2021-03-15 09-42-38](https://user-images.githubusercontent.com/1405703/111126494-1087ca80-8573-11eb-9d37-9dd6e82575ad.gif)
In the Java IDE, the toolbar is yellow, when running and hover. This does not happen with IDE2.

 - I have  noticed another issue, the toolbar hover has a different color:
Java IDE:
![screencast 2021-03-15 10-46-38](https://user-images.githubusercontent.com/1405703/111134341-cce58e80-857b-11eb-8c84-fea65e8ae63c.gif)

IDE2:
![screencast 2021-03-15 10-47-41](https://user-images.githubusercontent.com/1405703/111134468-f1da0180-857b-11eb-990c-acf1d5abd122.gif)

 - There is a pixel mismatch or what, one can clearly see how the toolbar shifts to the right a bit when the command is in process, then goes back.
![screencast 2021-03-15 10-49-06](https://user-images.githubusercontent.com/1405703/111134815-44b3b900-857c-11eb-9055-734805cf28f2.gif)

2021-03-15 09:53 UTC, kittaakos commented
I have restarted the build, it was failing due to some issues out of the context of the project:
```
    gyp http 500 https://electronjs.org/headers/v9.4.3/node-v9.4.3-headers.tar.gz
    gyp WARN install got an error, rolling back install
    gyp ERR! configure error 
    gyp ERR! stack Error: 500 response downloading https://electronjs.org/headers/v9.4.3/node-v9.4.3-headers.tar.gz
```
HTTP 5xx is a server error, there isn't much we could do. Hopefully, we get back the green build 🤞

2021-03-16 18:32 UTC, ubidefeo requested changes
the behaviour is correct, but disabled buttons (such as the debug button) should not receive a hover when they are disabled.

steps to reproduce:
- open a sketch
-  select Arduino UNO (does not support debugging)
- ensure the button is greyed out
- hover 
- verify it changes colour

2021-03-17 09:13 UTC, fstasi commented
> the behaviour is correct, but disabled buttons (such as the debug button) should not receive a hover when they are disabled.
> 
> steps to reproduce:
> 
>     * open a sketch
> 
>     * select Arduino UNO (does not support debugging)
> 
>     * ensure the button is greyed out
> 
>     * hover
> 
>     * verify it changes colour

@ubidefeo fixed, thanks for pointing that out. I'm glad I had a spare very old arduino uno to test it 🧪 

let me know if we are good to go

2021-03-17 16:07 UTC, ubidefeo approved these changes
LGTM

2021-03-17 16:32 UTC, merged