ci: use `ubuntu-latest` for the Linux build
arduino/arduino-ide pull request #1983
Opened 2023-03-29 08:07 UTC by kittaakos

### Motivation

The Linux build does not start occasionally, and GH Actions reports a canceled build. Also, the Linux container used by the IDE2 build is deprecated:

> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002

### Change description

Use `ubuntu-latest` on the CI.

### Other information

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2023-04-06 07:34 UTC, kittaakos commented
On a brand new Ubuntu 18.04, I get the following error at startup:

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/akitta/Downloads/arduino-ide_2.0.5-snapshot-90b1f67_Linux_64bit/resources/app/node_modules/nsfw/build/Release/nsfw.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/akitta/Downloads/arduino-ide_2.0.5-snapshot-90b1f67_Linux_64bit/resources/app/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1110:14) {
  code: 'ERR_DLOPEN_FAILED'
}

It works with 2.0.4.

2023-04-06 07:40 UTC, kittaakos commented
> ```shell
> /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/akitta/Downloads/arduino-ide_2.0.5-snapshot-90b1f67_Linux_64bit/resources/app/node_modules/nsfw/build/Release/nsfw.node)
> ```

Probably related: https://github.com/Axosoft/nsfw/issues/175

2023-04-06 16:56 UTC, per1234 commented
>related: https://github.com/Axosoft/nsfw/issues/175

That is similar, but different in that it is specific to the use of a Snapcraft package. Their distro has a modern version of GLibC installed (2.35), which is backwards compatible with the 2.33 the application is linked against, however, it seems the application is linked against a GLibC library in the Snap environment instead of the global installation in the distro.

The error you encountered when trying to start the build of Arduino IDE from this PR on a Ubuntu 18.04  machine is that it has an older version of GLibC (2.27) than the one Arduino IDE is linked against when build using the `ubuntu-latest` runner. The older versions of GLibC are not forwards compatible with applications that are linked against a newer version.

I didn't manage to find a way for the users to work around this problem by reconfiguring their system. So it seems we have two options:

- Drop compatibility with Linux distros that don't provide a compatible GLibC
- Change the build environment to link against an older version

Although unfortunate, I don't think it is completely unreasonable to drop support for Ubuntu 18.04 since its maintenance cycle [is about to end](https://ubuntu.com//blog/18-04-end-of-standard-support). However, I see the error also occurs with 20.04. I think dropping compatibility with such relatively recent distro releases will impact a significant number of users.

2023-04-06 16:58 UTC, per1234 requested changes

2023-04-06 16:58 UTC, per1234 commented on .github/workflows/build.yml
> +          - os: ubuntu-latest
```suggestion
          - os: ubuntu-20.04
```

This would be less impactful. This runner should remain available for some years to come.

2023-04-11 09:25 UTC, per1234 reviewed
https://github.com/arduino/arduino-ide/pull/1983/commits/fc0cc54e85ee0f00c46a3e955023c755300762cd restores compatibility with Ubuntu 20.04 as expected (retaining compatibility with Ubuntu 22.04 etc. due to the backwards compatibility of GLibC). However (as expected), the problem remains for Ubuntu 18.04 (and other Linux distros with an older version of GLibC):

```text
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_arduinLHEbAx/resources/app/node_modules/nsfw/build/Release/nsfw.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/tmp/.mount_arduinLHEbAx/resources/app/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1110:14) {
  code: 'ERR_DLOPEN_FAILED'
}
```

2023-04-13 07:39 UTC, kittaakos commented
We'll need to decide how to move forward. Thanks for the help!

----

When this PR gets merged, users won't be able to run IDE2 on Ubuntu 18.04 (or earlier).

@ubidefeo, as a follow-up, could you please create a pinned issue and describe the implication of this change?

2023-04-13 08:24 UTC, per1234 approved these changes
Thanks Akos!

I think the use of `ubuntu-20.04` is the best available immediate solution.

My hypothesis is that only a small number of the beta testers will be by the loss of compatibility of the tester and nightly builds with older Linux versions (e.g., Ubuntu 18.04) since that category of user is more likely to keep their system reasonably up to date.

And of course even if this change results in tester builds no being temporarily unavailable to some beta testers, that is still an improvement over the current situation where tester builds aren't available to anyone.

2023-04-13 09:12 UTC, merged