chore: Updated to `0.32.0-rc.1` CLI
arduino/arduino-ide pull request #1996
Opened 2023-04-05 09:35 UTC by kittaakos

### Motivation

Use a released version of the CLI in the IDE2.

### Change description

 - Updated to `0.32.0-rc.1` CLI and
 - Regenerated the JS/TS API for the CLI.

### Other information

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2023-04-07 05:34 UTC, per1234 requested changes

2023-04-07 05:34 UTC, per1234 commented on arduino-ide-extension/package.json
> +      "version": "0.32.0-rc.1"
```suggestion
      "version": "0.32.0"
```
The production release is now available:
https://github.com/arduino/arduino-cli/releases/tag/0.32.0

2023-04-12 09:57 UTC, per1234 requested changes

2023-04-12 09:57 UTC, per1234 commented on arduino-ide-extension/package.json
> +      "version": "0.32.1"
```suggestion
      "version": "0.32.2"
```
A patch release was made to fix [a regression](https://github.com/arduino/arduino-cli/issues/2144) in the previous release (and the `71a8576` development version previously in use): 

https://github.com/arduino/arduino-cli/releases/tag/0.32.2

2023-04-13 14:27 UTC, kittaakos commented
Thank you for the verification, Per!

2023-04-13 14:27 UTC, merged