ATL-1063: Integrated search in workspace into IDE
arduino/arduino-ide pull request #202
Opened 2021-03-11 13:47 UTC by kittaakos

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

What it does:
 - This PR integrates Theia's default `Search` view into the IDE2.
 - From now on, the `Search` view is part of the default layout, so when the user opens a new sketch, the `Search` view (with the magnifier icon. the monitor widget has a similar icon 😕) should be visible on the left sidebar.
 - This PR changes the order of the widgets on the left: `Board Manager`, `Lib Manager`, `Debug`, `Explorer` (this is hidden), `Search`, and `Outline` is the order. Then the rest of the views, if any.
 - This PR changes the default width of the sidebar views. When you open the view, it should require 200px width. It was 100px before. I thought increasing the width is a good thing, whenever I open a view, I have to change the horizontal dimension every time manually. What do you think?

Please review. Thank you!

2021-03-11 21:11 UTC, ubidefeo commented
hi Akos

>This PR integrates Theia's default Search view into the IDE2.
From now on, the Search view is part of the default layout, so when the user opens a new sketch, the Search view (with the magnifier icon. the monitor widget has a similar icon 😕) should be visible on the left sidebar.

This is a welcome addition to the IDE. Don't worry about the icon, we'll have to go through a final polishing of the theme at some point

>This PR changes the order of the widgets on the left: Board Manager, Lib Manager, Debug, Explorer (this is hidden), Search, and Outline is the order. Then the rest of the views, if any.

I toggled the Explorer and it comes before the Debugger
<img width="252" alt="Screenshot 2021-03-11 at 22 08 38" src="https://user-images.githubusercontent.com/1894487/110855277-6c71fb00-82b6-11eb-93ed-c8648bcca147.png">

> This PR changes the default width of the sidebar views. When you open the view, it should require 200px width. It was 100px before. I thought increasing the width is a good thing, whenever I open a view, I have to change the horizontal dimension every time manually. What do you think?

200px is a better option. I ran into the same issue you did and had to manually resize.
It was gonna turn into a task at some point :D

I'm fine with everything except the position of the Explorer if toggled. I'd place this at the very top, VS Code style ;)

2021-03-11 21:26 UTC, kittaakos commented
> Explorer if toggled. I'd place this at the very top, VS Code style ;)

👍 Even better. Thank you for the review.

2021-03-11 22:35 UTC, per1234 requested changes
OK, here I am again being a pain with my dirty sketches.

1. **File > Preferences**
2. Uncheck the box next to "Auto save".
3. Click the "OK" button.
4. Add the following text to a sketch: `foobar`
5. Click the search icon in the sidebar.
6. In the "Search" field", type `bar`
7. Click the downward pointing triangle button at the bottom left corner of "Search" field to reveal the "Replace" field.
8. In the "Replace" field", type `baz` - in the results section, the expected "foo~~bar~~baz" is shown.
9. Click "foo~~bar~~baz" to open the "Replace Preview" view in the editor. - the right side editor pane only shows "baz", rather than the expected "foobaz"

![Clipboard01](https://user-images.githubusercontent.com/8572152/110864418-f26e5180-8276-11eb-9a62-f074ef07fac0.png)

2021-03-12 12:29 UTC, kittaakos commented
I have fixed it in Theia and patched the IDE2 for the time being. Please review.

2021-03-14 09:16 UTC, per1234 approved these changes
Working great now. Thanks Akos!

2021-03-15 08:15 UTC, merged