Disable code signing when workflows run from forks
arduino/arduino-ide pull request #208
Opened 2021-03-12 08:36 UTC by rsora

This PR refactors the CI workflows to be more "fork friendly". 
If workflows are run on a PR generated by a fork, where secrets are not available, the CI will run skipping the signing steps, providing unsigned artifacts.

What this PR does:
- Skip Mac/Win code signing and Apple notarization only if PR comes from a fork
- Disable workflows entirely if the user enabled Github Actions in
their fork repo
- Add steps to help Mac users to test their forked code in BUILDING.md

2021-03-12 09:03 UTC, kittaakos requested changes
I added a few comments here and there. I will accept the PR if you re-submit it from a fork. Otherwise, we cannot verify if it works or not.

From the build [logs](https://github.com/arduino/arduino-ide/pull/208/checks?check_run_id=2093371745#step:5:225):
>  IS_FORK: false

2021-03-12 15:17 UTC, rsora commented
@kittaakos I'll open a new PR from a fork, so we can test the workflow mods I prepared as you requested.
I'll address all your change requests in the new PR and answer [to your question](https://github.com/arduino/arduino-ide/pull/208#discussion_r593004019) there. I'll close this one once we merge the new PR.
Is that ok for you?

2021-03-12 15:19 UTC, kittaakos commented
> Is that ok for you?

👍 Thank you!

2021-03-15 15:02 UTC, rsora commented
Superseded by #213

2021-03-15 15:02 UTC, closed without merging