feat: better error handling for cloud sketches
arduino/arduino-ide pull request #2092
Opened 2023-06-08 16:02 UTC by kittaakos

### Motivation

I am currently working on the server side to provide correct error codes in exceptional cases. This should help IDE2 to call the Cloud sketch APIs more efficiently.

This PR currently contains the expected behavior, nothing more. All new tests fail at this time.

_To be continued..._

### Change description

### Other information

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2023-06-08 16:04 UTC, kittaakos commented on arduino-ide-extension/src/test/browser/create-api.test.ts
> +    expect(resources.length > 0).to.be.true;
`expect(resources).to.be.not.empty;`

2023-06-08 18:50 UTC, kittaakos commented on arduino-ide-extension/src/test/browser/create-api.test.ts
> +    await rejects(createApi.deleteDirectory(posixPath), (thrown) =>
`readDirectory`

2023-10-06 05:08 UTC, per1234 requested changes

2023-10-06 05:08 UTC, per1234 commented on .github/workflows/build.yml
> +          CREATE_USERNAME: ${{ secrets.CREATE_USERNAME }}
```suggestion
          # The CREATE_* environment vars are only used to run tests. These secrets are optional. Dependent tests will
          # be skipped if not available.
          CREATE_USERNAME: ${{ secrets.CREATE_USERNAME }}
```

I think some explanation can be useful for contributors who want to run the workflow in their fork.

2023-10-06 09:36 UTC, per1234 approved these changes

2023-10-07 08:38 UTC, merged