adding a hyperlink to the README
arduino/arduino-ide pull request #2260
Opened 2023-10-15 07:18 UTC by lukasb1b

- [ ] PR addresses a single concern.
- [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
- [ ] PR title and description are properly filled.
- [ ] Docs have been added / updated (for bug fixes / features)

2023-10-16 06:01 UTC, per1234 requested changes

2023-10-16 06:01 UTC, per1234 commented on README.md
> +This repository contains the source code of the Arduino IDE 2.x. If you're looking for the old IDE, go to the (repository of the 1.x version)[https://github.com/arduino/Arduino].
```suggestion
This repository contains the source code of the Arduino IDE 2.x. If you're looking for the old IDE, go to the [repository of the 1.x version](https://github.com/arduino/Arduino).
```

You reversed the Markdown syntax:

https://www.markdownguide.org/basic-syntax/#links

In the future, please take more care to validate your contributions before submitting a pull request.

2023-10-16 08:44 UTC, per1234 approved these changes

2023-10-16 08:44 UTC, merged

2023-10-19 14:05 UTC, kittaakos commented
If it wasn't an accident, please squash merge next time. Thank you! Two distinct commits are unnecessary for a link update in the readme.

2023-10-19 14:13 UTC, per1234 commented
I apologize @kittaakos. I did notice it after I merged and was quite upset with myself about it since I care deeply about commit atomicity.