ATL-1128: make the new tab button easier to click
arduino/arduino-ide pull request #258
Opened 2021-03-23 08:02 UTC by fstasi

The active area for the new tab button is very small.
<img width="35" alt="image" src="https://user-images.githubusercontent.com/1636933/112112911-6af9da00-8bb6-11eb-9315-6eae6bbafa42.png">

This PR expands the active area by moving the padding from the container of the button to the button itself.

Padding changed because of the actual size of the chevron icon in the button.
___

Fixes #97 
[Jira Task](https://arduino.atlassian.net/browse/ATL-1128)

2021-03-23 14:16 UTC, ubidefeo requested changes
the clickable area is fine, but I get the contextual menu with a weird X offset
<img width="874" alt="Screenshot 2021-03-23 at 15 15 43" src="https://user-images.githubusercontent.com/1894487/112160652-a7dfc400-8bea-11eb-903f-96872d60bb97.png">

2021-03-24 08:58 UTC, fstasi commented
> the clickable area is fine, but I get the contextual menu with a weird X offset
> <img alt="Screenshot 2021-03-23 at 15 15 43" width="874" src="https://user-images.githubusercontent.com/1894487/112160652-a7dfc400-8bea-11eb-903f-96872d60bb97.png">

@ubidefeo this issue should be unrelated, plus, I'm not able to reproduce it. Did you resize the window or moved to another virtual desktop?

@kittaakos did you see this issue before?

2021-03-24 09:08 UTC, per1234 commented
I have experienced the same, which was related to changing the interface scale (see ATL-1080). @ubidefeo do you have any modifications to the **File > Preferences > Interface Scale** setting?

2021-03-24 09:11 UTC, kittaakos commented
> did you see this issue before?

No, I have not but the issue must be either somewhere here:

https://github.com/arduino/arduino-ide/blob/3fb087f1ada994b62ac6363b916b4849c7179a95/arduino-ide-extension/src/browser/contributions/sketch-control.ts#L59-L62

or was already fixed in Theia: https://github.com/eclipse-theia/theia/pull/9082. Maybe, there is nothing to do other than updating to the most recent `next` Theia. We're still on https://github.com/eclipse-theia/theia/commit/c9db9754

2021-03-24 09:13 UTC, fstasi commented
> > did you see this issue before?
> 
> No, I have not but the issue must be either somewhere here:
> 
> https://github.com/arduino/arduino-ide/blob/3fb087f1ada994b62ac6363b916b4849c7179a95/arduino-ide-extension/src/browser/contributions/sketch-control.ts#L59-L62
> 
> or was already fixed in Theia: [eclipse-theia/theia#9082](https://github.com/eclipse-theia/theia/pull/9082). Maybe, there is nothing to do other than updating to the most recent `next` Theia. We're still on [eclipse-theia/theia@c9db975](https://github.com/eclipse-theia/theia/commit/c9db9754)

let's address this in a separate PR then, thanks

2021-03-24 09:15 UTC, kittaakos commented on arduino-ide-extension/src/browser/style/main.css
> +
Can you please remove the whitespace changes? They're incorrect. Thanks!

2021-03-25 15:22 UTC, ubidefeo commented
@kittaakos @fstasi 
what should be done for this one, then?

2021-03-25 15:50 UTC, kittaakos commented
> what should be done for this one, then?

I would do the followings:
 - rebase https://github.com/arduino/arduino-ide/pull/231 and merge if it was approved,
 - rebase this PR from `main`, start a build see if the context menu bug still occurs.
   - If no, we're good. The issue has been fixed in Theia. We can merge this PR.
   - If yes, we need to fix it either as a follow-up or with this PR.

2021-03-25 17:08 UTC, ubidefeo commented
looks like a good plan
hope it works :)

ubi

> On 25 Mar 2021, at 16:51, Akos Kitta ***@***.***> wrote:
> 
> ﻿
> what should be done for this one, then?
> 
> I would do the followings:
> 
> rebase #231 and merge if it was approved,
> rebase this PR from main, start a build see if the context menu bug still occurs.
> If no, we're good. The issue has been fixed in Theia. We can merge this PR.
> If yes, we need to fix it either as a follow-up or with this PR.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-29 15:10 UTC, kittaakos commented
Can you please rebase the PR from the `main`? Also, please add the following to fix the issue when there are multiple "sketch-control" toolbar items. Locating them via their ID is flawed. Thank you!

```diff
diff --git a/arduino-ide-extension/src/browser/contributions/sketch-control.ts b/arduino-ide-extension/src/browser/contributions/sketch-control.ts
index 6e4010c..db0aa48 100644
--- a/arduino-ide-extension/src/browser/contributions/sketch-control.ts
+++ b/arduino-ide-extension/src/browser/contributions/sketch-control.ts
@@ -6,6 +6,7 @@ import { ContextMenuRenderer } from '@theia/core/lib/browser/context-menu-render
 import { Disposable, DisposableCollection } from '@theia/core/lib/common/disposable';
 import { URI, SketchContribution, Command, CommandRegistry, MenuModelRegistry, KeybindingRegistry, TabBarToolbarRegistry, open } from './contribution';
 import { ArduinoMenus } from '../menu/arduino-menus';
+import { EditorWidget } from '@theia/editor/lib/browser';
 
 @injectable()
 export class SketchControl extends SketchContribution {
@@ -24,15 +25,28 @@ export class SketchControl extends SketchContribution {
     registerCommands(registry: CommandRegistry): void {
         registry.registerCommand(SketchControl.Commands.OPEN_SKETCH_CONTROL__TOOLBAR, {
             isVisible: widget => this.shell.getWidgets('main').indexOf(widget) !== -1,
-            execute: async () => {
+            execute: async widget => {
                 this.toDisposeBeforeCreateNewContextMenu.dispose();
                 const sketch = await this.sketchServiceClient.currentSketch();
                 if (!sketch) {
                     return;
                 }
+                let target: HTMLElement | undefined = undefined;
+                if (widget instanceof EditorWidget) {
+                    const tabBar = this.shell.getTabBarFor(widget);
+                    if (tabBar) {
+                        const elements = document.querySelectorAll(`#${SketchControl.Commands.OPEN_SKETCH_CONTROL__TOOLBAR.id}`);
+                        for (const element of Array.from(elements)) {
+                            if (!target) {
+                                if (tabBar.node.contains(element)) {
+                                    target = element as HTMLElement;
+                                }
+                            }
+                        }
+                    }
+                }
 
-                const target = document.getElementById(SketchControl.Commands.OPEN_SKETCH_CONTROL__TOOLBAR.id);
-                if (!(target instanceof HTMLElement)) {
+                if (!target) {
                     return;
                 }
                 const { parentElement } = target;
```

![screencast 2021-03-29 17-07-15](https://user-images.githubusercontent.com/1405703/112857830-8d598f00-90b1-11eb-8dee-d2d0a589cd27.gif)

2021-03-30 07:54 UTC, merged

2021-04-08 14:26 UTC, ubidefeo commented
@fstasi 
Akos has found the wrong alignment bug and posted a patch
can you implement it?
#295