ATL-970: notification to last longer
arduino/arduino-ide pull request #260
Opened 2021-03-23 17:41 UTC by fstasi

With this PR I set the timeout of the following notification to 3 seconds (like other notifications in the IDE)
- burn bootloader
- verify sketch
- upload sketch

2021-03-23 18:31 UTC, ubidefeo commented
@fstasi 
the build fails, I'll test this tomorrow

2021-03-24 02:03 UTC, per1234 commented
@ubidefeo I reran the build and it passed this time so it's all ready for testing. The failure was only caused by a temporary external network outage; nothing related to the code here.

2021-03-24 07:35 UTC, kittaakos requested changes
The code change looks good to me, but the base branch is incorrect for this PR. This PR should not contain the keymap + preferences changes. Please fix it. Thank you!

2021-03-24 09:12 UTC, kittaakos approved these changes
Thank you! The code looks to me. 👍

Please merge once you have the final approval.

2021-03-31 14:26 UTC, rsora approved these changes
Tests on Win are 👍

2021-03-31 14:29 UTC, merged