Restore open sketches on startup
arduino/arduino-ide pull request #780
Opened 2022-01-27 13:26 UTC by msujew

Closes #384

Stores sketches which where closed immediately before the application closed in the `electronStore` of the main app. When restarting the application, the sketches are loaded and a dedicated window is launched for each of them.

The fix needs some special treatment for Windows. Due to my local setup, I was not able to test this on a POSIX system. although I'm quite certain it should work there as well.

2022-01-28 07:58 UTC, per1234 commented
Hi @msujew

> The fix needs some special treatment for Windows.

I'm not sure whether I understood correctly. Is the current build from this PR expected to work on Windows?

2022-01-28 11:18 UTC, msujew commented
@per1234 Yes, it definitely works on Windows, since it is the OS on my dev machine. On the other hand, it needs some testing to confirm it works on posix systems from your side.

2022-01-31 08:43 UTC, AlbyIanna approved these changes
Tested on MacOS. Looks very good to me! 🚀 
@silvanocerza would you please give it a try on Linux? 🙏

2022-01-31 10:22 UTC, silvanocerza approved these changes
Works fine for me on Linux. :+1:

2022-01-31 10:39 UTC, per1234 requested changes
It is not working for me on Windows 10

## To reproduce

1. Start the Arduino IDE.
   You now have a sketch open (I'll refer to it as "sketch a").
1. Open another sketch (I'll refer to it as "sketch b").
   You now have two sketches open.
1. Select **File > Quit** from the Arduino IDE menus.
1. Start the Arduino IDE

:bug: I now have two windows, each of which has "sketch b" open.

![image](https://user-images.githubusercontent.com/8572152/151779200-4290a941-d9bc-46bd-ae88-9fa6ff4fbfe1.png)

## Expected behavior

Starting IDE opens "sketch a" in one window and "sketch b" in the other.

2022-01-31 11:09 UTC, per1234 requested changes
The procedure I described above works correctly for me on Linux, however, I experienced a different problem on Linux:

## To reproduce

1. Start the Arduino IDE.
   You now have a sketch open (I'll refer to it as "sketch a").
1. Select **File > New** from the Arduino IDE menus.
   You now have a second sketch open, staged in a temporary folder (I'll refer to it as "new sketch").
1. Select **File > Quit** from the Arduino IDE menus.
1. Start the Arduino IDE

:bug: I now have two windows, each of which has "sketch a" open.

## Expected behavior

Starting IDE opens only a single window, containing "sketch a".

2022-01-31 13:24 UTC, msujew commented
@per1234 Thanks for the throughout review! I was able to reproduce both issues. The Windows one had some specific conditions: I was able to reproduce the issue by saving the sketch to a different drive.

The Linux issue stems from the OS deleting the temp folder. We now check for that before opening the window.

Both issues should now be hopefully fixed.

2022-01-31 15:00 UTC, silvanocerza commented
I confirm the issue on Linux reported by @per1234 is fixed, even creating multiple sketches and not saving them works with no issues.

2022-02-01 05:54 UTC, per1234 approved these changes
Everything working perfectly for me now on both Windows and Linux.

And indeed I did happen to have sketches "a" and "b" saved on a different drive from the IDE when I encountered the Windows issue I reported previously.

Thanks @msujew!

2022-02-02 14:42 UTC, ubidefeo commented
@msujew , it works on Mac OS Monterey, any chance we can save the windows state including positioning and size?

2022-02-02 16:33 UTC, ubidefeo commented
awesome!

2022-02-02 16:42 UTC, ubidefeo commented
@msujew 
I tested the build, and the first document still takes a small offset from TL corner.
I set the windows as
1: quadrant top left
2: quadrant bottom left
3: right side of the screen

When I relaunched I got this
![CleanShot 2022-02-02 at 17 40 34@2x](https://user-images.githubusercontent.com/1894487/152197817-c2a0484d-a91f-404a-bd3c-3b01743c7480.png)

2022-02-02 16:45 UTC, silvanocerza commented
What happens if I close the IDE on a secondary monitor, disconnect it and then open the IDE again? :eyes:

2022-02-02 17:32 UTC, msujew commented
@ubidefeo Do you mind retesting it? I believe the offset was introduced by a incorrect call to `avoidOverlap`. However, I'm not quite sure about that, since I couldn't test it on a Mac.

2022-02-02 17:44 UTC, per1234 commented
>close the IDE on a secondary monitor, disconnect it and then open the IDE again?

Arduino IDE 1.x has had problems with this sort of thing:
https://github.com/arduino/Arduino/issues/5581

2022-02-04 07:33 UTC, ubidefeo commented
@msujew 
I have not tested the very latest yet, but just launched the build I was testing and only one Sketch is open, aligned top-left.
I quit the IDE with two open Sketches and tried 3 times, the previous "session" is not restored

2022-02-07 11:16 UTC, msujew commented
@ubidefeo What environment are you using? Are you perhaps opening "new" sketches, which get automatically deleted by the OS after closing the IDE? This is what caused the issue [here](https://github.com/arduino/arduino-ide/pull/780#pullrequestreview-867698339), but now the IDE does not try to reopen deleted sketches.

2022-02-10 13:59 UTC, msujew commented
@per1234 @AlbyIanna I would merge this if that's alright with you? Having this PR in would make working on https://github.com/arduino/arduino-ide/issues/72 and https://github.com/arduino/arduino-ide/issues/370 easier.

2022-02-10 16:14 UTC, per1234 approved these changes
I tried the latest build out on both Windows and Linux and everything is still working perfectly for me.

So merging it is alright with me.

2022-02-11 09:57 UTC, merged