Enable opening the IDE from finder/explorer
arduino/arduino-ide pull request #835
Opened 2022-02-14 15:43 UTC by msujew

Closes #72
Closes #370
Closes #293

I needed a workaround to make MacOS wait for the `open-file` event, which is accomplished using the `openFilePromise`. However, I can't test this on Mac currently, so please get back to me if does not work correctly on Mac :)

2022-02-17 11:46 UTC, kittaakos commented
@msujew, I am happy to try it out. Can you please rebase? Currently, the app does not start. Thank you! See #836

```
/Applications/Arduino\ IDE.app/Contents/MacOS/Arduino\ IDE ; exit;
Starting backend process. PID: 10570
Failed to start the backend application:
Error: Cannot find module 'electron'
Require stack:
- /Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/grpc-client-provider.js
- /Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/core-client-provider.js
- /Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/library-service-server-impl.js
- /Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/arduino-ide-backend-module.js
- /Applications/Arduino IDE.app/Contents/Resources/app/src-gen/backend/server.js
- /Applications/Arduino IDE.app/Contents/Resources/app/src-gen/backend/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/grpc-client-provider.js:14:20)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/grpc-client-provider.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/core-client-provider.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/library-service-server-impl.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/arduino-ide-backend-module.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/src-gen/backend/server.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/src-gen/backend/main.js'
  ]
}
/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/@theia/core/lib/node/main.js:22
    throw reason;
    ^

Error: Cannot find module 'electron'
Require stack:
- /Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/grpc-client-provider.js
- /Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/core-client-provider.js
- /Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/library-service-server-impl.js
- /Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/arduino-ide-backend-module.js
- /Applications/Arduino IDE.app/Contents/Resources/app/src-gen/backend/server.js
- /Applications/Arduino IDE.app/Contents/Resources/app/src-gen/backend/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/grpc-client-provider.js:14:20)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/grpc-client-provider.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/core-client-provider.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/library-service-server-impl.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/node_modules/arduino-ide-extension/lib/node/arduino-ide-backend-module.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/src-gen/backend/server.js',
    '/Applications/Arduino IDE.app/Contents/Resources/app/src-gen/backend/main.js'
  ]
}
```

2022-02-17 14:26 UTC, per1234 reviewed
On Windows, it does "Enable opening the IDE from finder/explorer" for me. However, it does not provide the full functionality that I, and I'm certain the users as well expect. So I don't think it can be considered as a fix for https://github.com/arduino/arduino-ide/issues/370

1. Close any Arduino IDE windows that are already open.
1. Run the following command from PowerShell:
   ```
   & ".\Arduino IDE" "c:\Users\per\Documents\Arduino\SketchA\SketchA.ino"
   ```
   🙂 The IDE starts up with the "**SketchA**" sketch open.
1. Run the following command from PowerShell:
   ```
   & ".\Arduino IDE" "c:\Users\per\Documents\Arduino\SketchB\SketchB.ino"
   ```
   🙁 The existing Arduino IDE window with the "**SketchA**" sketch open is switched to.

My expected result from step (3) is that a new IDE window will open with the "**SketchB**" sketch open.

This expectation is how Arduino IDE 1.x works.

---

On Linux, running the equivalent of step 2 doesn't open "**SketchA**". It just starts the IDE with the most recent sketch, the same as running `./arduino-ide`.
 
Arduino IDE 1.x works the same on Linux as on Windows, in that you can pass sketch paths as an argument and open as many sketches in IDE windows as you like this way.

2022-02-22 20:03 UTC, msujew commented
@per1234 @kittaakos Thanks for the comments. I pushed some changes already a few days ago that should've addressed them.

2022-02-23 07:37 UTC, per1234 requested changes
Thanks @msujew. Unfortunately, when using [the build](https://github.com/arduino/arduino-ide/actions/runs/1859406310) from https://github.com/arduino/arduino-ide/pull/835/commits/38585e8415c17e6e97522ca2af80441ebdcb8888 (2.0.0-rc4-snapshot.7b5c9d7-snapshot-7b5c9d7), it is not working at all for me.

## Set a known baseline state for the IDE

1. Start the Arduino IDE directly.
1. Select **File > Open...** from the Arduino IDE menus.
1. Open `c:\Users\per\Documents\Arduino\SketchA\SketchA.ino`
1. Close all IDE windows other than the one that has "**SketchA**" open.
1. Close the IDE window with "**SketchA**" open.

We now know that when the IDE is started without any file association, it should have "**SketchA**" open.

## Test file association

1. Run the following command from PowerShell:
   ```
   & ".\Arduino IDE" "c:\Users\per\Documents\Arduino\SketchB\SketchB.ino"
   ```
   🙁 The Arduino IDE starts with the "**SketchA**" sketch open rather than the expected "**SketchB**".

2022-02-23 07:46 UTC, per1234 commented
Hi @msujew. I have a question: is this intended to provide any support for Linux?

The reason I ask is because the addressed issues are for Windows and macOS and you didn't mention anything about Linux (perhaps even implicitly excluding it from the scope via the mention only of "finder/explorer").

Although I would eventually like to see feature parity with Arduino IDE 1.x achieved in this respect for Linux as well, there is no reason that must be within the scope of this PR. I mentioned my Linux results in my first review only because I had tried it out of curiosity.

If this PR is intended to affect Linux, I'm happy to test on that OS as well. macOS is not so accessible to me so hopefully someone else can help with that.

2022-02-23 12:20 UTC, msujew commented
@per1234 Previously I used `platform === 'darwin` or `platform === 'win32'` to switch the behavior. I now use `isOSX` (or `!isOSX`) for that, so Windows and Linux behavior should be the same now.

I also pushed some changes which made parsing the arguments a bit more lenient, I think it was too strict when going through the arguments, so it rejected some valid `*.ino` paths. I downloaded the latest artifact from GH Actions and the feature works well for me now.

2022-02-23 15:39 UTC, merged

2023-09-09 05:30 UTC, dongwanpianist commented
Hello! This is my second day of using Arduino IDE on my MacOS (Monterey 12.6.8) by downloading and installing arduino-ide_2.2.1_macOS_64bit.dmg from https://www.arduino.cc/en/software , and I have encountered the same problem (as of September 8th, 2023)

1. When I open `Arduino IDE.app` from `~/Application` or `Dock`:
    * It behaves well—of course, it is the basic initializer of the app instance...
    * as soon as the app is initialized, it shows a new window that opens the recently closed workspace folder (or a new workspace, if recent workspace is missing)
    * The MacOS menubar shows the menus linked with the edit window, like this:
          <img width="428" alt="image" src="https://github.com/arduino/arduino-ide/assets/64175445/1a1bb42e-c82d-4e40-b6c7-6edb9391bae2">
2. When I double-click an `.ino` file from `Finder`
    * The app is initialized, but no window is appeared.
    * The MacOS menubar's `File` menu only has a disabled "Close Window" submenu, like this:
        <img width="377" alt="image" src="https://github.com/arduino/arduino-ide/assets/64175445/277acc4b-506b-4799-861c-c3be0995c7be">
    * Including above, any notable behavior of the menu is described below.
        * working menu:
            1) `Arduino IDE > About arduino-ide` (of course, this "Arduino IDE" menu has the events between OS and App instance)
            2) `Arduino IDE > Quit arduino-ide`
        - not working menu:
            1) Everything in `File` (disabled `Close Window` is the only visible submenu)
            2) Everything in `View` (all submenu below doesn't show any change on screen)
                <img width="230" alt="image" src="https://github.com/arduino/arduino-ide/assets/64175445/99f44668-045e-43b6-835e-10c6432ef23b">
            3) Everything in `Window` (its submenus are all disabled and visible)
            4) `Help` (provided by the OS, not useful except typing about or quit)

So, I guess there is something wrong during `openFilePromise` or `open-file`. Could any of you take a look at the problem? Thank you very much!