add PR template file
arduino/arduino-ide pull request #838
Opened 2022-02-15 11:24 UTC by fstasi

### Motivation
Standardize the structure of arduino-ide PRs

### Change description
added the `PULL_REQUEST_TEMPLATE.md` file

### Other information

### Reviewer checklist

* [ ] PR address a single concern.
* [ ] PR title and description are properly filled.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] Docs have been added / updated (for bug fixes / features)

2022-02-15 11:36 UTC, per1234 requested changes

2022-02-15 11:36 UTC, per1234 commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] PR address a single concern.
```suggestion
* [ ] PR addresses a single concern.
```
Grammar nitpick.

2022-02-15 11:36 UTC, per1234 commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
```suggestion
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
```
It is more efficient to do things in this order. There is no point in evaluating the quality of title and description if the PR is only to be closed as a duplicate.

2022-02-15 17:42 UTC, per1234 approved these changes

2022-03-03 13:53 UTC, AlbyIanna approved these changes

2022-03-03 13:54 UTC, merged