fix IDE updater commands
arduino/arduino-ide pull request #872
Opened 2022-02-28 13:27 UTC by AlbyIanna

### Motivation
IDE updater commands are not working how expected. They work, but they are not giving any feedback to the user.

### Change description
Remove useless commands. Leave only the "Check for Arduino IDE updates" command. When launching this command, if there is an update available, it opens the update dialog. If there isn't any update available or some error occurs, it shows a notification message.

### Reviewer checklist

* [ ] PR addresses a single concern.
* [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-ide/pulls) before creating one)
* [ ] PR title and description are properly filled.
* [ ] Docs have been added / updated (for bug fixes / features)

2022-02-28 13:59 UTC, fstasi approved these changes

2022-03-01 04:53 UTC, per1234 commented
@AlbyIanna if you still want me to check this out, please do a rebase to trigger a build. The build workflow is configured to only run on PRs submitted to the `main` branch, so it didn't run on the previous push. Now that the base has been changed to `main` it will run on the next update to the PR.

But I see Francesco already gave it the :+1:, so it is good to merge right away.

2022-03-01 08:34 UTC, AlbyIanna commented
@per1234 ✅ done!

2022-03-01 08:59 UTC, AlbyIanna commented
@per1234 I've just realised I'm not updating the channel configuration immediately when the user changes the channel preference. It's not done until the next IDE start-up. I'm going to fix it in this PR because I think it's pertinent.

2022-03-01 11:18 UTC, AlbyIanna commented
@per1234 Done. Now it should work as expected, that is when you change the channel or the update URL and then check for updates, the updater will use the correct channel/URL.

P.S.: I've noticed the expand/collapse icons in the bottom-right notifications are "invisible". Fixing it in another PR.

2022-03-01 14:52 UTC, per1234 requested changes

2022-03-01 14:59 UTC, AlbyIanna commented on arduino-ide-extension/src/browser/ide-updater/ide-updater-commands.ts
> +          `There are no recent updates available the Arduino IDE`
❤️

2022-03-01 16:34 UTC, merged